using System;
using System.Diagnostics.CodeAnalysis;

namespace Rxmxnx.PInvoke.Tests.SourceGenerator
{
    [ExcludeFromCodeCoverage]
    internal static class StringSet
    {
        public static readonly String[] Set = new String[]
        {
            "Hello, World! 🌍👋" /* English, Length = 15 */,
            "¡Hola! ¿Cómo estás? 😊👍" /* Spanish, Length = 24 */,
            "你好，你怎么样？👀💬" /* Chinese, Length = 14 */,
            "こんにちは、お元気ですか？🌸😃" /* Japanese, Length = 20 */,
            "Привет, как дела? 👋😊" /* Russian, Length = 18 */,
            "Bonjour, comment ça va? 🌞🤔" /* French, Length = 23 */,
            "Cześć, jak się masz? 👋😄" /* Polish, Length = 20 */,
            "مرحبا، كيف حالك؟ 😃🌷" /* Arabic, Length = 20 */,
            "สวัสดีครับ สบายดีหรือเปล่า? 🌴👍" /* Thai, Length = 29 */,
            "שלום, מה נשמע? 😉👋" /* Hebrew, Length = 17 */,
            "I ❤️ coding in C#! 💻🤖" /* English, Length = 23 */,
            "Je suis en train d'apprendre le code en C# 🤓👨‍💻" /* French, Length = 47 */,
            "¡El lenguaje de programación C# es increíble! 😎👨‍💻" /* Spanish, Length = 50 */,
            "C# является одним из моих любимых языков программирования 😍💻" /* Russian, Length = 59 */,
            "私はC#でコーディングするのが大好きです！👨‍💻❤️" /* Japanese, Length = 29 */,
            "Coding in C# ist einfach super! 🚀💻" /* German, Length = 36 */,
            "Programowanie w C# to frajda! 😄💻" /* Polish, Length = 34 */,
            "أحب البرمجة باستخدام لغة C# ❤️👨‍💻" /* Arabic, Length = 38 */,
            "ฉันชอบการเขียนโปรแกรมด้วย C# มาก! 👩‍💻💖" /* Thai, Length = 34 */,
            "אני אוהב לתכנת ב-C#! 💻😍" /* Hebrew, Length = 23 */,
            "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed vel fermentum nisl. Morbi commodo ultrices nibh, eget congue ligula malesuada id. 👀🔍📚" /* Latin, Length = 116 */,
            "生活在这个世界上是一种神圣的经历，值得珍惜。让我们珍惜这个美好的经历，永远不要放弃我们的梦想。🌅🌟💭" /* Chinese, Length = 39 */,
            "Для успешного развития бизнеса необходимо иметь не только капитал, но и правильную стратегию и хорошую команду.💼💰👨‍💼" /* Russian, Length = 82 */,
            "A veces, las cosas más simples son las más hermosas. Solo tienes que detenerte y apreciarlas.🌺🌷🌸" /* Spanish, Length = 72 */,
            "Le sourire est la clé qui ouvre de nombreuses portes. Souriez et le monde sourira avec vous.😊🌞🌈" /* French, Length = 82 */,
            "Cieszę się, że mogę dziś z Tobą porozmawiać. Jak się masz? Co nowego u Ciebie?🤔👋👀" /* Polish, Length = 85 */,
            "لا يوجد شيء مستحيل في هذه الحياة ، إذا كان لديك إرادة ومثابرة ، يمكنك تحقيق أي شيء تريده.👊🌟🙌" /* Arabic, Length = 88 */,
            "เมื่อเราเรียนรู้ใหม่ ๆ สิ่งที่เกิดขึ้นก็คือการเปลี่ยนแปลงที่ดีขึ้นเรื่อย ๆ ในชีวิตของเรา 💪🌟📚" /* Thai, Length = 106 */,
            "Hallo! Wie geht es Ihnen heute? Ich hoffe, Sie haben einen wunderbaren Tag!🌞🤗👋" /* German, Length = 74 */,
            "Ciao a tutti! Spero che voi stiate passando una giornata meravigliosa piena di energia e buonumore!💪🌞👋" /* Italian, Length = 101 */,
            "אם תרצו, זה לא חלום. כל דבר אפשרי, רק צריך להתחיל. אז מה בוחרים לעשות היום? 🤔💭💪" /* Hebrew, Length = 83 */,
            "Kunnes emme ole vahvempia yhdessä, emme voi olla vahvoja erikseen. Yhdessä olemme enemmän.💪🌟🤝" /* Finnish, Length = 92 */,
            "Не бойся начинать сначала. Бойся только оставаться на месте.👊🔥🚀" /* Russian, Length = 68 */,
            "A vida é uma grande aventura. Descubra o mundo e viva intensamente cada momento. 🌍🌞💪" /* Portuguese, Length = 81 */,
            "自分を信じて、自分の道を進むことが成功への鍵です。信じることができると、何でも達成できます。💪🌟🚶‍♀️" /* Japanese, Length = 101 */,
            "La vie est un long chemin à parcourir. Il y aura des hauts et des bas, mais c'est le voyage qui compte. 🌅🌍🚶‍♀️" /* French, Length = 94 */,
            "La felicidad no es un destino, es un camino. Vive el momento y disfruta cada paso del camino.🌞💃🌈" /* Spanish, Length = 88 */,
            "당신이 믿는 것을 따라가면 언제나 올바른 길을 가게 됩니다. 이길이 쉽지 않더라도, 끝까지 밀고 나가면 됩니다.💪🌟👣" /* Korean, Length = 101 */,
            "In questa vita abbiamo solo una possibilità, quindi dobbiamo viverla al massimo. Sii coraggioso e segui il tuo cuore!💪💖🌞" /* Italian, Length = 98 */,
            "Nézd meg az életet egy szép sztorinak, amelynek a főszereplője te vagy. Minden kalandnak megvan a maga tanulsága.💫🌅📚" /* Hungarian, Length = 103 */,
            "Life is not about waiting for the storm to pass, it's about learning to dance in the rain.☔💃🌞🌈" /* English, Length = 88 */,
            "Sólo aquellos que se arriesgan a ir demasiado lejos pueden descubrir hasta dónde se puede llegar.🚀🏃‍♂️💪" /* Spanish, Length = 95 */,
            "生きている間にやりたいことがあるなら、今すぐやり始めましょう。後悔しないためにも、行動を起こすことが大切です。💪🌟🚶‍♀️" /* Japanese, Length = 107 */,
            "La vie est faite de moments. Profitez des petits et des grands, et n'oubliez jamais de sourire!😊🌞🌈" /* French, Length = 90 */,
            "Manche Dinge im Leben brauchen Zeit und Geduld, aber am Ende lohnt sich jede Mühe.💪🌅🌳" /* German, Length = 78 */,
            "Sự thành công không đến từ sự may mắn, mà đến từ sự kiên trì và nỗ lực không ngừng nghỉ.💪🌟🌈" /* Vietnamese, Length = 93 */,
            "A vida é uma oportunidade incrível. Não perca tempo com coisas insignificantes e faça cada dia valer a pena!💫🌞💪" /* Portuguese, Length = 99 */,
            "Life is a journey, and every step we take is a chance to learn, grow, and become the best version of ourselves.🌍🌱💪" /* (English), Length = 97 */,
            "La vie est une aventure, chaque pas nous permet d'apprendre, de grandir et de devenir la meilleure version de nous-mêmes.🌍🌱💪" /* (French), Length = 115 */,
            "A vida é curta demais para viver com medo. Arrisque, tente coisas novas e nunca se arrependa de ter vivido intensamente.🌞💪" /* (Portuguese), Length = 90 */,
            "Hakuna matata significa no preocuparse por el resto de tus días. Vive al máximo cada momento y nunca te arrepentirás.🦁🌅🌞" /* (Spanish), Length = 104 */,
            "Vita est peregrinatio, et omnis gradus ducit ad discendum, crescendum et ad optima ex nobis fieri.🌍🌱💪" /* (Latin), Length = 82 */,
            "生活不是等待暴风雨过去，而是学会在雨中跳舞。抓住每个机会，成为更好的自己。☔💃🌞" /* (Chinese), Length = 75 */,
            "Život je cesta, každý krok nám dáva šancu učiť sa, rásť a stať sa najlepšou verziou seba samého.🌍🌱💪" /* (Slovak), Length = 100 */,
            "La vida es un viaje, cada paso es una oportunidad para aprender, crecer y convertirse en la mejor versión de uno mismo.🌍🌱💪" /* (Spanish), Length = 107 */,
            "Vie ist Abenteuer, jeder Schritt ist Chance zu lernen, zu wachsen und die beste Version von uns selbst zu werden.🌍🌱💪" /* (German), Length = 107 */,
            "Sevgi köprüsü, dil farklılıklarını aşar, herkesi birleştirir.🌍❤️ (Turkish), Length = 59",
            "Lebensfreude ist ein Paradies, das wir alle betreten sollten. Joie de vivre is a paradise that we should all enter.😊🌅" /* (German, French), Length = 109 */,
            "Mi corazón late con fuerza, como el ritmo de una samba. And my heart beats strong, like the rhythm of a samba.🎶❤️" /* (Spanish, English), Length = 98 */,
            "Quel che è stato fatto, è stato fatto. Ciò che importa è ciò che faremo adesso. What is done, is done. What matters is what we do now.💪🌞" /* (Italian, English), Length = 112 */,
            "Mundo maravilloso, lleno de colores y de vida. Wonderful world, full of colors and life.🌍🌈🌺" /* (Spanish, English), Length = 78 */,
            "Эх, жизнь, жизнь... Почему ты такая трудная? Oh, life, life... Why are you so difficult?😔🌅" /* (Russian, English), Length = 83 */,
            "De temps en temps, nous devons tous nous arrêter et admirer la beauté du monde. From time to time, we all need to stop and admire the beauty of the world.🌍🌺" /* (French, English), Length = 124 */,
            "Ich liebe dich, mon amour, te quiero, ti amo... no matter how you say it, the feeling is the same.❤️💕" /* (German, French, Spanish, Italian), Length = 98 */,
            "Viviamo tutti sotto lo stesso cielo, ma non tutti vediamo gli stessi colori. We all live under the same sky, but we don't all see the same colors.🌍🌈" /* (Italian, English), Length = 115 */,
            "Kimi no koe wa tooku hanarete mo, kokoro no naka ni zutto ikite iru. Even if your voice is far away, it will always live inside my heart.❤️🎶" /* (Japanese), Length = 95 */,
            "Hayat dolu dolu yaşanmalı, her anı kıymetli. Life should be lived to the fullest, every moment is precious.💪🌅" /* (Turkish), Length = 78 */,
            "C'est incroyable, how much we can accomplish when we work together!🤝💪🏼" /* (French, English), Length = 86 */,
            "Estar presente en el momento es clave para vivir la vida al máximo. Being present in the moment is key to living life to the fullest.🌅🧘‍♀️" /* (Spanish, English), Length = 115 */,
            "La vita è un'avventura, non smettere mai di esplorare! Life is an adventure, never stop exploring!🌍🌱🔍" /* (Italian), Length = 90 */,
            "Не взирая на языковые барьеры, мы можем найти общий язык с каждым. Despite language barriers, we can find a common language with anyone.🗣️👥" /* (Russian, English), Length = 128 */,
            "Vivre dans l'amour, c'est la plus belle chose que l'on puisse faire. Living in love is the most beautiful thing one can do.❤️💕" /* (French), Length = 94 */,
            "Güneşli günlerde bile yağmur yağabilir, hayat da bazen böyledir. Even on sunny days, it can rain, life can be like that sometimes.☀️🌧️" /* (Turkish), Length = 107 */,
            "El mundo está lleno de maravillas por descubrir, solo necesitamos abrir nuestros ojos y nuestra mente. The world is full of wonders to discover, we just need to open our eyes and our mind.👀🌎" /* (Spanish, English), Length = 130 */,
            "彼方に見える、青い空と海。海外の友達と一緒に旅行することは最高です。 The blue sky and sea visible in the distance. Traveling with foreign friends is the best.🌊✈️" /* (Japanese), Length = 105 */,
            "Zaman akıp giderken, hiçbir şey değişmez sanmayın. Her an yeniden doğarız. While time flows, don't think that nothing changes. We are reborn every moment.🕰️🌅" /* (Turkish), Length = 117 */,
            "Être soi-même est la clé pour trouver le bonheur. Being oneself is the key to finding happiness.🗝️😊" /* (French), Length = 80 */,
            "जब ज़िन्दगी आपको नीचे धकेलती है, तब आपके हाथों में सिर्फ एक ही विकल्प होता है - उठना। When life pushes you down, there's only one option in your hands - get up.👊🏼🌅" /* (Hindi), Length = 121 */,
            "كلما كنت محاطًا بأشخاص مختلفين عنك، كلما تعلمت أشياء جديدة. The more you're surrounded by people different from you, the more you learn new things.🌎👥" /* (Arabic), Length = 126 */,
            "世界是你的舞台。愿你成为最好的演员。The world is your stage. May you become the best actor.🌍🎭" /* (Chinese), Length = 74 */,
            "När livet ger dig citroner, gör saft och hoppas att någon uppskattar din dryck. When life gives you lemons, make juice and hope someone appreciates your drink.🍋🧃" /* (Swedish), Length = 118 */,
            "Если бы я имел столько денег, сколько меня кто-то любит, то я был бы миллионером. If I had as much money as someone loves me, I'd be a millionaire.💰❤️" /* (Russian), Length = 97 */,
            "להיות יהודי זה להיות אני עם היסטוריה עשירה וקצת מזל, וגם להפך. To be a Jew is to be myself with a rich history and some luck, and vice versa.🕍✡️" /* (Hebrew), Length = 109 */,
            "El amor es como el viento, no se puede ver pero se puede sentir. Love is like the wind, you can't see it but you can feel it.💕🌬️" /* (Spanish), Length = 77 */,
            "እባክዎ በእኛ ስለሆነ ደግሞ አብሮን ተስፋ ይሁኑ። If you're not interested in us, please leave us alone.👋🏽🌍" /* (Amharic), Length = 87 */,
            "Svaka šala ima svoje zrno istine. Every joke has a grain of truth in it.😂🌾" /* (Croatian), Length = 50 */,
            "कुछ लोग सोचते हैं, खुद को संभालना मुश्किल है, लेकिन मैं उन्हें बताना चाहता हूं, जो वास्तव में टूट गए हैं, वे सिर्फ एक नई शुरुआत के लिए खुला हैं। 🌅💪" /* Hindi, Length = 93 */,
            "Estou muito feliz hoje porque vou me encontrar com meus amigos para comemorar o aniversário de um deles. 🎉🎂👭👬" /* Portuguese, Length = 89 */,
            "私たちはこれまでで一番幸せでした。彼らは子供たちを育てていて、私たちは一緒に成長しました。👩‍👧‍👦🌸" /* Japanese, Length = 67 */,
            "Жизнь это цветение, а цветение это красота.💐😍🌺" /* Russian, Length = 43 */,
            "La vida es una aventura, y cada día es una oportunidad para explorar el mundo y descubrir nuevas maravillas.🌍🌞🌴" /* Spanish, Length = 94 */,
            "Jeder Mensch ist einzigartig und hat seine eigenen Stärken und Schwächen. Wir sollten uns auf das konzentrieren, was uns stark macht und uns erlauben, zu wachsen und uns zu entwickeln.💪🌱" /* German, Length = 125 */,
            "মানব জীবনের বিভিন্ন উদ্দেশ্য এবং লক্ষ্যগুলি আমাদের দরজার পেছনে সেট করে দিয়েছে। আমরা সেটি নির্ধারণ করে নেব এবং আমাদের জীবন সম্পর্কে উচিত সিদ্ধান্ত নিবে। 🌅🌳" /* Bengali, Length = 132 */,
            "كل ما نريده هو السلام في العالم والمساواة بين جميع البشر. 🕊️🌍" /* Arabic, Length = 67 */,
            "आपका स्वागत है! Welcome! 🙏🌟🎉" /* Hindi, English, Length = 28 */,
            "Le jour de l'indépendance est un rappel de la lutte pour la liberté et la dignité humaine. 🇫🇷🇲🇦🌍" /* French, Arabic, Length = 96 */,
            "Ich liebe dich bis zum Mond und zurück. 🌕❤️🚀" /* German, Length = 39 */,
            "아름다운 일몰을 보러 가자! Let's go see a beautiful sunset! 🌅🌺" /* Korean, English, Length = 50 */,
            "Je suis content d'être ici 🇫🇷👋" /* French, Length = 28 */,
            "Viel Spaß beim Programmieren! 🤖👨‍💻" /* German, Length = 34 */,
            "Hola, ¿cómo estás? 🇪🇸😊" /* Spanish, Length = 22 */,
            "Привет, как дела? 🇷🇺👋" /* Russian, Length = 22 */,
            "你好，很高兴认识你 🇨🇳👋" /* Chinese, Length = 24 */,
            "Ciao, come stai? 🇮🇹😊" /* Italian, Length = 20 */,
            "สวัสดีครับ 🇹🇭👋" /* Thai, Length = 12 */,
            "नमस्ते, क्या हाल है? 🇮🇳👋" /* Hindi, Length = 24 */,
            "Γεια σου, τι κάνεις; 🇬🇷👋" /* Greek, Length = 22 */,
            "こんにちは、元気ですか？ 🇯🇵😊" /* Japanese, Length = 22 */,
            "Salam, apa khabar? 🇲🇾👋" /* Malay, Length = 20 */,
            "Sveiki, kaip sekasi? 🇱🇹👋" /* Lithuanian, Length = 22 */,
            "Merhaba, nasılsın? 🇹🇷😊" /* Turkish, Length = 20 */,
            "שלום, מה שלומך? 🇮🇱👋" /* Hebrew, Length = 20 */,
            "ਸਤਿ ਸ੍ਰੀ ਅਕਾਲ, ਕਿਵੇਂ ਹੋ? 🇮🇳👋" /* Punjabi, Length = 30 */,
            "வணக்கம், எப்படி இருக்கிறாய்? 🇮🇳👋" /* Tamil, Length = 36 */,
            "مرحبا، كيف حالك؟ 🇸🇦👋" /* Arabic, Length = 22 */,
            "Sziasztok, hogyan vagyunk? 🇭🇺👋" /* Hungarian, Length = 26 */,
            "Përshëndetje, si jeni? 🇦🇱👋" /* Albanian, Length = 22 */,
            "Hallo, wie geht es dir? 🇩🇪😊" /* German, Length = 24 */,
            "Das ist ein Test, um zu sehen, ob dieser Text verschiedene Sprachen und Zeichen enthält." /* German, Length = 82 */,
            "Esta es una prueba para ver si este texto incluye varios idiomas y caracteres." /* Spanish, Length = 84 */,
            "C'est un test pour voir si ce texte contient plusieurs langues et caractères différents." /* French, Length = 89 */,
            "Это тест, чтобы проверить, содержит ли этот текст разные языки и символы." /* Russian, Length = 86 */,
            "هذا اختبار لمعرفة ما إذا كان هذا النص يحتوي على عدة لغات وحروف." /* Arabic, Length = 78 */,
            "這是一個測試，以查看此文本是否包含多種語言和字符。" /* Traditional Chinese, Length = 67 */,
            "これは、このテキストにさまざまな言語と文字が含まれているかどうかを確認するテストです。" /* Japanese, Length = 75 */,
            "이것은이 텍스트에 다양한 언어와 문자가 포함되어 있는지 확인하기 위한 테스트입니다." /* Korean, Length = 70 */,
            "هذا اختبار برای دیدن اینکه آیا این متن شامل چندین زبان و نویسه مختلف است یا نه." /* Persian, Length = 94 */,
            "Bu metin farklı diller ve karakterler içerip içermediğini görmek için bir testtir." /* Turkish, Length = 76 */,
            "Il mio gatto 🐱 è il re della casa, ma ogni tanto si comporta come un vero 🐶." /* Italian, Length = 83 */,
            "यह टेक्स्ट अलग-अलग भाषाओं और चिह्नों को शामिल करता है, लेकिन यह हिंदी भाषा में है। 🙏🕉️" /* Hindi, Length = 117 */,
            "Этот текст содержит различные языки, символы и математические формулы: ∑i=0n xi = x1 + x2 + ... + xn" /* Russian, Length = 102 */,
            "Esta é uma mensagem de teste para demonstrar que é possível incluir símbolos e emojis em um texto 🌞✉️💻" /* Portuguese, Length = 101 */,
            "Αυτός ο κείμενο περιλαμβάνει διάφορες γλώσσες, ειδικούς χαρακτήρες και σύμβολα, όπως η εξίσωση της ζωής: ∫e^x dx = e^x + C" /* Greek, Length = 162 */,
            "このテキストは、異なる言語、記号、および絵文字を含んでいます。私たちの犬 🐶 は、あなたを幸せにするのに十分な愛情を持っています ❤️" /* Japanese, Length = 116 */,
            "Bu metin, farklı diller, semboller ve matematiksel işaretleri içerir. Ayrıca, 🎉🎂🎁 gibi özel emoji'ler de vardır." /* Turkish, Length = 99 */,
            "Dieser Text enthält verschiedene Sprachen, Symbole und Emojis, wie z.B. die Glück bringende 🍀 und die fröhliche 🌈." /* German, Length = 105 */,
            "这个文本包含不同的语言，符号和表情符号，例如：👋😊🌹以及数学公式：a^2 + b^2 = c^2" /* Simplified Chinese, Length = 92 */,
            "Este texto incluye diferentes idiomas, símbolos y emojis, como el símbolo del infinito ♾️ y el emoji de la bandera 🇺🇸." /* Spanish, Length = 107 */,
            "La vida es un regalo, no un derecho. Aprovecha cada momento que se te da. 🎁⏰💖" /* Spanish, Length = 63 */,
            "Le passé est derrière, le futur est inconnu, mais le présent est un cadeau. 🎁🎉🕰️" /* French, Length = 68 */,
            "私たちが見ているものはすべて影響を受け、影響を与えています。 🌎🌟🤝" /* Japanese, Length = 49 */,
            "O amor é um mistério que ninguém sabe explicar, mas todos querem experimentar. 💕💘😍" /* Portuguese, Length = 68 */,
            "Η ζωή είναι μια περιπέτεια, με τα πάνω και τα κάτω της, που αξίζει να ζήσουμε. 🌄🌊🏞️" /* Greek, Length = 80 */,
            "जीवन एक अनुभव है, जिसमें से हर पल एक सीखने, बढ़ने और अपने सबसे अच्छे संस्करण बनने का मौका है। 🙏🌺💪" /* Hindi, Length = 126 */,
            "Жизнь полна приключений, и каждый шаг, который мы делаем, - это возможность учиться, расти и стать лучшей версией себя. 🏔️🌅🌱" /* Russian, Length = 118 */,
            "生命是一個旅程，我們迈出的每一步都是學習、成長和成為最好的自己的機會。🌏🌱💪" /* Chinese, Length = 49 */,
            "Het leven is een avontuur, met ups en downs, dat de moeite waard is om te leven. 🏔️🌅🌿" /* Dutch, Length = 80 */,
            "Das Leben ist ein Abenteuer, mit all seinen Höhen und Tiefen, das es wert ist, gelebt zu werden. 🌄🌊🌱" /* German, Length = 95 */,
            "The path to success is never easy, but with determination and hard work, anything is possible. 💪🏆💼" /* English, Length = 79 */,
            "El futuro pertenece a aquellos que creen en la belleza de sus sueños. 🌟💭✨" /* Spanish, Length = 64 */,
            "La felicità è un viaggio, non una destinazione. Bisogna godere del viaggio, non solo della meta. 🚀🌞🌈" /* Italian, Length = 89 */,
            "La vie est belle ! 🌺🌸🌼" /* French, Length = 18 */,
            "梦想是心灵的火花。✨" /* Chinese, Length = 11 */,
            "La felicidad no es tener lo que quieres, sino querer lo que tienes. 💕" /* Spanish, Length = 64 */,
            "ஒரு சுதந்திர உலகம் எனக்கு வேண்டும். 🌍" /* Tamil, Length = 27 */,
            "Η ζωή είναι ωραία. 🌞" /* Greek, Length = 18 */,
            "All work and no play makes Jack a dull boy. ⌨️" /* English, Length = 42 */,
            "A vida é uma aventura para aqueles que se arriscam. 🌟" /* Portuguese, Length = 50 */,
            "الصبر مفتاح الفرج. 🔑" /* Arabic, Length = 16 */,
            "समय का महत्व सबको बताया जाता है। ⏰" /* Hindi, Length = 30 */,
            "生きる意味を見つけるために、あなたは自分の内側を探る必要があります。🧘‍♀️" /* Japanese, Length = 41 */,
            "Nada es imposible, la palabra misma dice 'soy posible'. 💪" /* Spanish, Length = 56 */,
            "ਹਰ ਕਦਮ ਤੇ ਸਿੱਖਣ ਦਾ ਮੌਕਾ ਹੈ। 📚" /* Punjabi, Length = 28 */,
            "Le bonheur est un état d'esprit. 😊" /* French, Length = 32 */,
            "أعطِ الحبّ للآخرين، واستقبِلهُ بذِراعيْن مفتوحتيْن. 💕" /* Arabic, Length = 52 */,
            "Wir können den Wind nicht ändern, aber die Segel anders setzen. ⛵" /* German, Length = 58 */,
            "우리는 항상 어디에서나 올바른 것을 선택할 수 있습니다.👍" /* Korean, Length = 35 */,
            "எல்லாத்துக்கும் ஒரு தெய்வம் உண்டு. 🙏" /* Tamil, Length = 23 */,
            "The sun ☀️ is shining and the birds 🐦 are singing. Life is beautiful! 🌸💖✨" /* English, Length = 57 */,
            "Ich liebe es, durch die Straßen von Paris 🇫🇷 zu bummeln und die Schönheit der Stadt zu genießen. 🥐🍷💐" /* German, Length = 94 */,
            "Мне очень нравится гулять по набережной в Санкт-Петербурге 🏰 и любоваться видом на реку Неву. 🌉🚣‍♀️❤️" /* Russian, Length = 99 */,
            "我喜欢用我的笔记本电脑 💻 写代码 🖥️，它让我感觉很聪明 🤓。" /* Chinese, Length = 53 */,
            "Je suis en train de préparer une salade 🥗 pour le déjeuner, j'adore les légumes frais 🍅🥕🥬! " /* French, Length = 86 */,
            "Mi pasión es tocar el piano 🎹 y componer música 🎼, es una forma de expresión maravillosa 🌟." /* Spanish, Length = 95 */,
            "Μου αρέσει να περπατάω στην παραλία 🏖️ και να ακούω τον ήχο των κυμάτων 🌊, με χαλαρώνει πολύ. ☀️" /* Greek, Length = 102 */,
            "私は本を読むことが好きです 📚。特に、哲学や心理学の本を読むのが好きです。🧐" /* Japanese, Length = 54 */,
            "Ho appena finito di guardare una serie televisiva 📺 molto interessante sulla vita degli astronauti 🚀, mi ha fatto sognare ad occhi aperti. 🚀✨" /* Italian, Length = 118 */,
            "أحب أن أشاهد الأفلام الهندية 🎥 والاستمتاع بالألوان والرقصات الجميلة 🎶💃. لغتهم تبدو مثل الموسيقى 🎵." /* Arabic, Length = 123 */,
            "Minha banda favorita é o Pink Floyd 🎸, eles têm músicas incríveis e cheias de significado. 🎵🤘" /* Portuguese, Length = 82 */,
            "Jeg elsker at bage kager 🎂 og kager 🧁, det er en af mine yndlingsaktiviteter i fritiden. 🍪🍰🥧" /* Danish, Length = 96 */,
            "¡La vida es una aventura emocionante llena de posibilidades infinitas! 🌟🌈✨" /* Spanish, Length = 59 */,
            "生命是一個充滿挑戰和機會的旅程，讓我們好好把握！🌻🌺🌸" /* Traditional Chinese, Length = 58 */,
            "Когда вы думаете, что достигли своего предела, думайте о том, что вы еще можете сделать. 💪🔥🚀" /* Russian, Length = 77 */,
            "每个人都有潜力成为自己想要成为的人，不断努力追求自己的梦想和目标！💫🌟✨" /* Simplified Chinese, Length = 63 */,
            "À la recherche du temps perdu 📚🌸🕰️" /* French, 34 */,
            "Tôi là người Việt Nam 🇻🇳❤️" /* Vietnamese, 21 */,
            "El amor es un fuego que arde sin ser visto 🔥❤️" /* Spanish, 42 */,
            "昨夜のコンサートは最高でした 🎶🎤" /* Japanese, 19 */,
            "ምን ያህል ብሎ ማለት ይቻላል? 😕🤔" /* Amharic, 18 */,
            "Ο κόσμος είναι ένα μέρος πανέμορφο 🌍🌞" /* Greek, 30 */,
            "അവൻ കയ്യിൽ ഒരു പൂവിനെ കൊണ്ട് വന്നു 🌺💐" /* Malayalam, 26 */,
            "Saya suka makan nasi goreng 🍚🌶️" /* Indonesian, 23 */,
            "我喜欢吃火锅和麻辣烫 🔥🍲" /* Mandarin Chinese, 18 */,
            "Kakvo krasivo izlagane na cvetqta 🌺🌼" /* Bulgarian, 31 */,
            "Czasami warto zaryzykować, żeby osiągnąć sukces 💪🚀" /* Polish, 48 */,
            "Каждый день дарит новые возможности 🌅🌈" /* Russian, 36 */,
            "La vida es demasiado corta para no comer postres 🍰🍨" /* Spanish, 44 */,
            "Ich liebe es, auf dem Oktoberfest zu tanzen 🍻🎉" /* German, 38 */,
            "Il y a des fleurs partout pour qui veut bien les voir. 🌸🌺🌼" /* French, 49 */,
            "Los sueños son el alimento del alma. 🌙✨🌟" /* Spanish, 37 */,
            "Καλημέρα σε όλους! ☀️🍃" /* Greek, 23 */,
            "Der Weg ist das Ziel. 🏞️🥾🧭" /* German, 25 */,
            "Умейте радоваться жизни, она прекрасна. 🌅🌺💖" /* Russian, 45 */,
            "En la vida lo más importante es dar amor y recibirlo. ❤️💕💞" /* Spanish, 50 */,
            "Μην ανησυχείτε για αυτό που δεν μπορείτε να αλλάξετε. 🙏🌺" /* Greek, 54 */,
            "Le sourire est une clé magique qui ouvre bien des portes. 😊🔑🚪" /* French, 49 */,
            "Das Leben ist ein Abenteuer, also genieße es. 🏞️🌄🌊" /* German, 47 */,
            "Счастье не в деньгах, а в душе. 💰❌💖" /* Russian, 34 */,
            "The speed of light in a vacuum is a universal constant denoted by c = 299,792,458 m/s. ⚡️🔬🌌" /* Physics, 82 */,
            "The Pythagorean theorem states that in a right triangle, the square of the length of the hypotenuse is equal to the sum of the squares of the lengths of the other two sides. 📐🔍🧮" /* Math, 123 */,
            "Newton's second law of motion states that the acceleration of an object is directly proportional to the force applied to it and inversely proportional to its mass. F = ma. 🚀📈🔭" /* Physics, 129 */,
            "The golden ratio, also known as the divine proportion, is a mathematical ratio that appears in many forms of art, architecture, and nature. φ = (1 + √5)/2. 📐🎨🌿" /* Math, 120 */,
            "Einstein's famous equation E = mc² shows that mass and energy are equivalent and interchangeable. 💡🧐⚛️" /* Physics, 77 */,
            "The quadratic formula can be used to find the roots of any quadratic equation of the form ax² + bx + c = 0. 🧮🔍🌳" /* Math, 96 */,
            "The law of cosines relates the sides and angles of a non-right triangle: c² = a² + b² - 2ab cos(C). 📐🔍🌅" /* Math, 92 */,
            "The Schrödinger equation is a fundamental equation in quantum mechanics that describes the time evolution of a quantum state. 🧐🔬⚛️" /* Physics, 97 */,
            "The Pythagorean theorem can be extended to three dimensions with the formula c² = a² + b² + h², where h is the height of the right triangle's altitude. 📐🔍🧭" /* Math, 122 */,
            "In relativity, the spacetime interval between two events is a measure of the distance between them in four-dimensional spacetime. Δs² = c²Δt² - Δx² - Δy² - Δz². 🚀🧐🔭" /* Physics, 163 */,
            "La vie est comme une boîte de chocolats, on ne sait jamais sur quoi on va tomber." /* French, Length = 70 */,
            "科学是关于我们世界的奥秘和探究。🔬🌌👨‍🔬" /* Chinese, Length = 32 */,
            "Математика - это язык, на котором говорят науки о нашем мире. 🧮🌐📊" /* Russian, Length = 63 */,
            "La física es la ciencia que trata de la materia, la energía, el espacio y el tiempo. ⚛️🔭🌌" /* Spanish, Length = 72 */,
            "数学は世界中のありとあらゆる物事を理解するための言葉である。🧮🌐📊" /* Japanese, Length = 47 */,
            "Die Physik erforscht die fundamentalen Gesetze der Natur und beschreibt, wie sie funktioniert. 🔬⚛️🌌" /* German, Length = 84 */,
            "Matematika adalah bahasa yang digunakan untuk menggambarkan alam semesta dan segala isinya. 🧮🌐📊" /* Indonesian, Length = 76 */,
            "Η φυσική είναι η επιστήμη που ασχολείται με τη μελέτη της φύσης και της κίνησης των αντικειμένων. 🔭⚛️🌌" /* Greek, Length = 107 */,
            "Fizik, madde, enerji, uzay ve zamanı ele alan bir bilim dalıdır. 🔬⚛️🌌" /* Turkish, Length = 72 */,
            "الفيزياء هي العلم الذي يتناول دراسة المادة والطاقة والزمان والمكان. 🔭⚛️🌌" /* Arabic, Length = 78 */,
            "A velocidade da luz no vácuo é de aproximadamente 299.792.458 metros por segundo (m/s). 🚀🔭" /*Portuguese, Length = 81*/,
            "La teoría de la relatividad de Einstein establece que la energía y la masa son equivalentes y están relacionadas por la famosa ecuación E = mc². 🌌🔬" /*Spanish, Length = 105*/,
            "在三角形ABC中，AB = 3，AC = 4，BC = 5，那么它是个直角三角形。📐🔍" /*Chinese, Length = 67*/,
            "La force est une grandeur physique qui mesure l'interaction entre deux objets. Elle s'exprime en newtons (N). ⚛️🔬" /*French, Length = 96*/,
            "In der Quantenmechanik beschreibt die Wellenfunktion den Zustand eines Systems und seine möglichen Messergebnisse. 🌌🧪" /*German, Length = 108*/,
            "В квантовой механике волновая функция описывает состояние системы и её возможные измерения.🌌🧪" /*Russian, Length = 94*/,
            "Στα μαθηματικά, οι πράξεις μεταξύ των αριθμών ακολουθούν τους κανόνες της αλγεβρας. 🔢📚" /*Greek, Length = 89*/,
            "En physique quantique, l'effet tunnel est un phénomène où une particule traverse une barrière de potentiel même si sa quantité d'énergie est inférieure à la hauteur de la barrière. 🌌🧪" /*French, Length = 163*/,
            "हम ज्यामिति में दो बिंदुओं के बीच की दूरी को दो निश्चित बिंदुओं के बीच की दूरी के रूप में प्रदर्शित करते हैं। 📐📏" /*Hindi, Length = 146*/,
            "La forza di gravità tra due oggetti dipende dalle loro masse e dalla distanza tra di essi, e si calcola con la legge di gravitazione universale di Newton. 🌌🔬" /*Italian, Length = 142*/,
            "La vitesse de la lumière est une constante fondamentale de l'univers, notée c en physique, qui a une valeur d'environ 299 792 458 mètres par seconde." /* French, 111 */,
            "El número de oro, también conocido como la proporción áurea, es una relación matemática que se encuentra en la naturaleza y en el arte." /* Spanish, 103 */,
            "A Lei de Coulomb descreve a força eletrostática entre duas partículas carregadas. Ela é uma das leis fundamentais da eletromagnetismo." /* Portuguese, 121 */,
            "Παραμετροποίηση είναι η διαδικασία μετατροπής μιας συνάρτησης σε μια εκδοχή της, που είναι ευκολότερη να αναλυθεί ή να χειριστεί." /* Greek, 142 */,
            "Fizikte, vektörlerin boyu ve yönü ile ilgili kavramları tanımlamak için kullanılan araç, vektör olarak adlandırılır." /* Turkish, 106 */,
            "El teorema de Pitágoras nos dice que en un triángulo rectángulo, el cuadrado de la hipotenusa es igual a la suma de los cuadrados de los catetos. 📐🔍🧮" /* Spanish, 98 */,
            "La loi de Coulomb est une loi physique qui décrit la force électrique entre deux particules chargées. Elle est basée sur la constante de Coulomb, la charge des particules et la distance qui les sépare. ⚡️🔍🧲" /* French, 129 */,
            "A fórmula de Euler, e^(ix) = cos(x) + i sin(x), relaciona os números complexos, a trigonometria e a exponencial. É uma das fórmulas mais famosas e importantes da matemática. 🧮🔍📈" /* Portuguese, 136 */,
            "La théorie de la relativité restreinte d'Einstein stipule que la vitesse de la lumière est la même pour tous les observateurs, indépendamment de leur mouvement. Elle a des implications importantes pour notre compréhension de l'espace et du temps. 🚀🔭⏱️" /* French, 204 */,
            "La teoría de la relatividad general de Einstein describe la relación entre la materia, la energía y la geometría del espacio-tiempo. Propone que la presencia de masa y energía distorsiona el espacio-tiempo, lo que produce la gravedad. 🌌🔭🪐" /* Spanish, 223 */,
            "A geometria fractal é uma área da matemática que lida com objetos geométricos que exibem auto-similaridade em diferentes escalas. É uma ferramenta importante em muitas áreas, incluindo a física, a biologia e a economia. 🧮🔍🌿" /* Portuguese, 188 */,
            "La mécanique quantique est une théorie physique qui décrit le comportement des particules subatomiques. Elle repose sur des concepts tels que la superposition, l'intrication et la dualité onde-particule. 🌌🔬🧬" /* French, 161 */,
            "O teorema de Fermat afirma que não existem soluções inteiras positivas para a equação x^n + y^n = z^n para n>2. Foi um problema famoso na matemática por séculos antes de ser provado por Andrew Wiles em 1994. 🧮🔍🕰️" /* Portuguese, 205 */,
            "Die Schrödingergleichung ist eine fundamentale Gleichung der Quantenmechanik, die den zeitlichen Verlauf von Quantenzuständen beschreibt. Sie ist benannt nach ihrem Entdecker, Erwin Schrödinger. 🔬🔍🧪" /* German, 151 */,
            "La teoria delle stringhe è una teoria fisica che cerca di unificare la relatività generale e la meccanica quantistica. Propone che le particelle fondamentali non siano puntiformi, ma piuttosto stringhe vibrazionali. 🌌🔬🧬" /* Italian, 194 */,
            "La gravità è una forza fondamentale dell'universo che tiene insieme tutto ciò che esiste. 🌌🪐🔭" /* Italian, Length = 70 */,
            "El teorema de Pitágoras establece que en un triángulo rectángulo, el cuadrado de la hipotenusa es igual a la suma de los cuadrados de los catetos. 📐🔍🧑‍🏫" /* Spanish, Length = 109 */,
            "A lei de Ohm afirma que a corrente que flui através de um condutor é diretamente proporcional à diferença de potencial e inversamente proporcional à resistência. ⚡️🔌🧑‍🔬" /* Portuguese, Length = 125 */,
            "La loi de Coulomb énonce que la force électrostatique entre deux charges est proportionnelle au produit de ces charges et inversement proportionnelle au carré de la distance qui les sépare. ⚡️🔋🧑‍🏭" /* French, Length = 193 */,
            "Die Schrödinger-Gleichung beschreibt die Wellenfunktion eines Teilchens und erlaubt Vorhersagen über dessen Verhalten in einem quantenmechanischen System. 🧪🔬👨‍🔬" /* German, Length = 162 */,
            "La ley de la conservación de la energía establece que la energía no se puede crear ni destruir, solo se puede transformar de una forma a otra. 🔋⚡️🔄" /* Spanish, Length = 111 */,
            "A fórmula de Einstein E = mc² estabelece que a energia (E) contida em um objeto de massa (m) é igual à massa multiplicada pelo quadrado da velocidade da luz (c). 🔭🧑‍🔬🪐" /* Portuguese, Length = 171 */,
            "La loi de l'attraction universelle de Newton décrit la force gravitationnelle entre deux corps et est responsable de la formation des planètes, des étoiles et des galaxies. 🌌🪐🔭" /* French, Length = 174 */,
            "Das Pythagoreische Theorem besagt, dass in einem rechtwinkligen Dreieck das Quadrat der Hypotenuse gleich der Summe der Quadrate der Katheten ist. 📐🔍🧑‍🏫" /* German, Length = 161 */,
            "La ley de la reflexión de Snell establece que el ángulo de incidencia de un rayo de luz en una superficie de separación de dos medios es igual al ángulo de refracción. 🔍🌈💡" /* Spanish, Length = 121 */,
            "La théorie de la relativité restreinte d'Einstein a révolutionné notre compréhension de l'espace et du temps. E=mc² 🚀⏱️🔭" /* French, Length = 86 */,
            "El álgebra es una rama de las matemáticas que estudia las operaciones y las estructuras algebraicas. x² + y² = r² 🔢📈🔍" /* Spanish, Length = 90 */,
            "Quantum mechanics is a fundamental theory in physics that describes the behavior of matter and energy at a microscopic level. ĤΨ = iħ∂Ψ/∂t 🔬🌀🌌" /* English, Length = 110 */,
            "A física moderna nos permite compreender as partículas subatômicas e as forças fundamentais da natureza. F = ma 🧪🦠🔬" /* Portuguese, Length = 94 */,
            "Der Satz des Pythagoras ist ein grundlegendes mathematisches Konzept, das in der Geometrie weit verbreitet ist. a² + b² = c² 📐🔍🧮" /* German, Length = 97 */,
            "La mécanique quantique est une théorie fondamentale de la physique qui décrit le comportement de la matière et de l'énergie à l'échelle microscopique. ĤΨ = iħ∂Ψ/∂t 🔬🌀🌌" /* French, Length = 118 */,
            "A teoria das cordas é uma tentativa de unificar a física quântica e a relatividade geral em uma teoria consistente. E = hf 🪕🌌🔬" /* Portuguese, Length = 97 */,
            "La teoría de la relatividad general de Einstein describe la relación entre el espacio, el tiempo y la gravedad. Gμν = 8πTμν/c⁴ ⏱️🔭🪐" /* Spanish, Length = 117 */,
            "Die Quantenmechanik beschreibt das Verhalten von Materie und Energie auf mikroskopischer Ebene und ist eine grundlegende Theorie der Physik. ĤΨ = iħ∂Ψ/∂t 🔬🌀🌌" /* German, Length = 122 */,
            "La fisica delle particelle studia le particelle elementari e le interazioni fondamentali che costituiscono l'universo. F = ma 🔭🪐🌌" /* Italian, Length = 102 */,
            "Quantum mechanics is the study of the behavior of matter and energy at the smallest scales of atoms and subatomic particles. 🔬⚛️🌌" /* English, Length = 96 */,
            "La linguistique est l'étude scientifique du langage et de sa structure. 📚🗣️🔍" /* French, Length = 76 */,
            "El átomo es la unidad básica de la materia, compuesta por protones, neutrones y electrones. ⚛️🧪🔬" /* Spanish, Length = 89 */,
            "Die Philosophie beschäftigt sich mit Fragen nach dem Sinn des Lebens, der Existenz und der Wahrheit. 🤔📚🧐" /* German, Length = 101 */,
            "Biology is the study of living organisms and their interactions with each other and the environment. 🌿🦠🔬" /* English, Length = 94 */,
            "La chimie est la science qui étudie la composition, les propriétés et les transformations de la matière. 🧪🌡️🧬" /* French, Length = 104 */,
            "A célula é a unidade básica da vida, composta por membrana, citoplasma e núcleo. 🧬🔬🔍" /* Portuguese, Length = 94 */,
            "Geometry is the branch of mathematics that studies the properties and relationships of points, lines, and shapes. 🔍📐🔺" /* English, Length = 100 */,
            "La physique est la science qui étudie la nature et les propriétés de la matière et de l'énergie. 🧬⚛️🌌" /* French, Length = 103 */,
            "Chemical reactions involve the rearrangement of atoms to form new substances with different properties. 🔬🧪🔥" /* English, Length = 95 */,
            "The universe is full of mysteries waiting to be uncovered. 🪐🔭🌌" /* English, Length = 53 */,
            "La probabilité d'un événement est égale au nombre de cas favorables divisé par le nombre de cas possibles. 🎲🔢📊" /* French, Length = 106 */,
            "A teoria da relatividade de Einstein revolucionou nossa compreensão do tempo e do espaço. ⏰🕰️🌌" /* Portuguese, Length = 85 */,
            "Die Wahrscheinlichkeit eines Ereignisses ist gleich der Anzahl der günstigen Fälle geteilt durch die Anzahl der möglichen Fälle. 🎲🔢📊" /* German, Length = 116 */,
            "El ADN es la molécula fundamental de la vida, conteniendo toda la información genética necesaria para el desarrollo y mantenimiento de los seres vivos. 🧬🔬🌱" /* Spanish, Length = 145 */,
            "人工智能是现代科技发展中的一项重要成果，正在深刻改变我们的生活。🤖💻📈" /* Chinese, Length = 72 */,
            "La linguistique étudie les langues et les systèmes linguistiques, ainsi que leur évolution et leur diversité à travers le temps et l'espace. 📚🗣️🌍" /* French, Length = 147 */,
            "La chimie est la science qui étudie la composition, les propriétés et les transformations de la matière. 🔬🧪🌡️" /* French, Length = 90 */,
            "La filosofía es la disciplina que se ocupa de cuestiones fundamentales como la existencia, la verdad, la moral y la mente humana. 🧠💭🤔" /* Spanish, Length = 121 */,
            "In der Geometrie untersucht man die Eigenschaften von Formen, Größen und Positionen im Raum. 🔺🔳🔲" /* German, Length = 93 */,
            "The chemical reaction between sodium and chlorine results in the formation of table salt, NaCl.🧪🔥🧂" /* English, 64 */,
            "La masse de l'Univers est dominée par de la matière noire, une forme inconnue de matière qui ne produit ni n'absorbe de lumière.🌌👻🔭" /* French, 115 */,
            "Die Kinetische Energie eines Objekts ist direkt proportional zu seiner Masse und der Geschwindigkeit, mit der es sich bewegt.🚀💫📈" /* German, 100 */,
            "En física cuántica, la superposición es el fenómeno en el que un objeto cuántico se encuentra en varios estados a la vez.🔬🌟🌈" /* Spanish, 109 */,
            "Η αντίσταση είναι η ιδιότητα ενός υλικού που εμποδίζει τη ροή ηλεκτρικού ρεύματος.🔌⚡️🔬" /* Greek, 93 */,
            "La gravité est une force qui attire deux corps l'un vers l'autre en raison de leur masse. ⚙️🪐🔭" /* French, Length = 79 */,
            "A inércia é a tendência de um objeto em repouso a permanecer em repouso e de um objeto em movimento a continuar se movendo em linha reta. 🏃‍♀️🌎🔬" /* Portuguese, Length = 102 */,
            "التكاثف هو تغير الحالة الفيزيائية للمادة من الغاز إلى السائل بفعل الضغط والتبريد. 🌬️💧🌡️" /* Arabic, Length = 96 */,
            "在三角形中，正弦是对边与斜边之比，余弦是邻边与斜边之比，正切是对边与邻边之比。🔍🔢📏" /* Chinese, Length =   78 */,
            "La lógica es el estudio de los principios y métodos utilizados para distinguir el razonamiento correcto del incorrecto. 🧐🤔📚" /* Spanish, Length = 95 */,
            "O ciclo do carbono é o processo natural pelo qual o carbono é trocado entre a biosfera, a atmosfera, os oceanos e a crosta terrestre. 🌍🌡️🔬" /* Portuguese, Length = 114 */,
            "जैविक उपचार नामक विज्ञान हमें वनस्पतियों, जीवों और बाक्टीरिया के उपयोग से दवाओं को बनाना सिखाता है। 🌿💊🧫" /* Hindi, Length = 109 */,
            "En linguistique, la morphologie est l'étude de la formation des mots et de leur structure interne. 🔎📚🗣️" /* French, Length = 90 */,
        };
    }
}