<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003">

    <Import Project="..\MonoProject.props"/>
    <Import Project="..\MonoFacades\System.Text.Json.Mono.props"/>

    <PropertyGroup>
        <AssemblyName>$(AssemblyName).mono</AssemblyName>
    </PropertyGroup>

    <ItemGroup>
        <EmbeddedResource Include="Mono.ILLink.Descriptors.xml">
            <LogicalName>$(AssemblyName).xml</LogicalName>
        </EmbeddedResource>
    </ItemGroup>

</Project>
