<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>netstandard2.1</TargetFramework>
    </PropertyGroup>

    <ItemGroup>
        <EmbeddedResource Include="..\..\MonoFacades\Rxmxnx.PInvoke.Json\Mono.ILLink.Descriptors.xml">
            <LogicalName>LegacyAppTest.Core.xml</LogicalName>
        </EmbeddedResource>
    </ItemGroup>
    <ItemGroup>
        <Compile Include="..\..\MonoFacades\Rxmxnx.PInvoke.Json\*JsonConverter.cs">
            <Link>%(RecursiveDir)%(Filename)%(Extension)</Link>
        </Compile>
        <Compile Include="..\..\ApplicationTest\Rxmxnx.PInvoke.ApplicationTest\**\*.cs">
            <Link>%(RecursiveDir)%(Filename)%(Extension)</Link>
        </Compile>
        <Compile Remove="..\..\ApplicationTest\Rxmxnx.PInvoke.ApplicationTest\Program.cs" />
        <Compile Remove="..\..\ApplicationTest\Rxmxnx.PInvoke.ApplicationTest\bin\**;..\..\ApplicationTest\Rxmxnx.PInvoke.ApplicationTest\obj\**;" />
    </ItemGroup>
    <ItemGroup>
        <None Remove="..\.editorconfig" />
    </ItemGroup>
    <Import Project="..\LegacyProject.props" />

</Project>
