<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003">

    <!-- LIMITED_LEGACY_SUPPORT -->
    <PropertyGroup>
        <TestSdkVersion>17.3.3</TestSdkVersion>
        <VisualStudioRunnerVersion Condition="'$(TargetFramework)' == 'netcoreapp2.0'">2.4.1</VisualStudioRunnerVersion>
        <VisualStudioRunnerVersion Condition="'$(TargetFramework)' != 'netcoreapp2.0'">2.4.3</VisualStudioRunnerVersion>
        <CoverletColectorVersion Condition="'$(TargetFramework)' == 'net452'">6.0.0</CoverletColectorVersion>
        <CoverletColectorVersion Condition="'$(TargetFramework)' != 'net452'">6.0.4</CoverletColectorVersion>
        <TaskExtensionsVersion Condition="'$(TargetFramework)' == 'net461'">4.5.4</TaskExtensionsVersion>
        <TaskExtensionsVersion Condition="$([MSBuild]::IsTargetFrameworkCompatible('$(TargetFramework)', 'net462'))">4.6.3</TaskExtensionsVersion>
    </PropertyGroup>
    <!-- LEGACY_SUPPORT -->
    <PropertyGroup Condition="'$(TargetFramework)' == 'netcoreapp3.1' Or '$(TargetFramework)' == 'net5.0'">
        <TestSdkVersion>17.13.0</TestSdkVersion>
        <VisualStudioRunnerVersion>2.4.5</VisualStudioRunnerVersion>
    </PropertyGroup>
    <!-- OLD_SUPPORTED -->
    <PropertyGroup Condition="'$(TargetFramework)' == 'net6.0' Or '$(TargetFramework)' == 'net7.0'">
        <TestSdkVersion>17.13.0</TestSdkVersion>
        <VisualStudioRunnerVersion>3.0.2</VisualStudioRunnerVersion>
    </PropertyGroup>
    <!-- NETFRAMEWORK_SUPPORT -->
    <PropertyGroup Condition="'$(TargetFrameworkIdentifier)' == '.NETFramework' And $([MSBuild]::IsOSPlatform('WINDOWS'))">
        <TestSdkVersion Condition="$([MSBuild]::IsTargetFrameworkCompatible('$(TargetFramework)', 'net462'))">18.9.0</TestSdkVersion>
        <VisualStudioRunnerVersion Condition="$([MSBuild]::IsTargetFrameworkCompatible('$(TargetFramework)', 'net462'))">2.4.5</VisualStudioRunnerVersion>
        <VisualStudioRunnerVersion Condition="$([MSBuild]::IsTargetFrameworkCompatible('$(TargetFramework)', 'net472'))">4.0.0</VisualStudioRunnerVersion>
    </PropertyGroup>
    <!-- CURRENT_SUPPORTED -->
    <PropertyGroup Condition="$([MSBuild]::IsTargetFrameworkCompatible('$(TargetFramework)', 'net8.0'))">
        <TestSdkVersion>18.9.0</TestSdkVersion>
        <VisualStudioRunnerVersion>4.0.0</VisualStudioRunnerVersion>
    </PropertyGroup>

    <ItemGroup Condition="'$(TargetFrameworkIdentifier)' != '.NETStandard'">
        <PackageReference Condition="'$(TargetFramework)' == 'netcoreapp2.0'" Include="Microsoft.NETCore.App" Version="2.0.9"/>
        <PackageReference Condition="'$(TargetFramework)' == 'netcoreapp2.1'" Include="Microsoft.NETCore.App" Version="2.1.30"/>
        <PackageReference Include="Microsoft.NET.Test.Sdk" Version="$(TestSdkVersion)"/>
        <PackageReference Include="xunit.runner.visualstudio" Version="$(VisualStudioRunnerVersion)">
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
            <PrivateAssets>all</PrivateAssets>
        </PackageReference>
        <PackageReference Include="coverlet.collector" Version="$(CoverletColectorVersion)">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers</IncludeAssets>
        </PackageReference>
    </ItemGroup>
    <ItemGroup Condition="'$(TargetFrameworkIdentifier)' == '.NETFramework'">
        <PackageReference Condition="'$(TaskExtensionsVersion)' != ''" Include="System.Threading.Tasks.Extensions" Version="$(TaskExtensionsVersion)"/>
        <PackageReference Condition="!$([MSBuild]::IsOSPlatform('WINDOWS'))" Include="Microsoft.TestPlatform.ObjectModel" Version="$(TestSdkVersion)"/>
    </ItemGroup>

</Project>
