<Project Sdk="Microsoft.NET.Sdk">

    <Import Project="..\Tests.props"/>
    <Import Condition="'$(TargetFramework)' == 'netstandard2.0' Or '$(TargetFramework)' == 'netstandard2.1'" Project="..\MonoTests.targets"/>
    <Import Condition="'$(TargetFramework)' != 'netstandard2.0' And '$(TargetFramework)' != 'netstandard2.1' And '$(MultipleFrameworkTest)' == 'true'" Project="..\DotnetCoreAppTests.targets"/>

    <ItemGroup>
        <Using Condition="'$(TargetFrameworkIdentifier)' != '.NETStandard'" Include="Xunit"/>
        <Using Condition="'$(TargetFrameworkIdentifier)' == '.NETStandard'" Include="NUnit.Framework"/>
        <Using Include="AutoFixture"/>
        <Using Include="System.Buffers"/>
        <Using Include="System.Diagnostics"/>
        <Using Include="System.Diagnostics.CodeAnalysis"/>
        <Using Include="System.Globalization"/>
        <Using Include="System.Net"/>
        <Using Include="System.Reflection"/>
        <Using Include="System.Runtime.CompilerServices"/>
        <Using Include="System.Runtime.InteropServices"/>
        <Using Include="System.Text"/>

        <Using Include="Rxmxnx.PInvoke.Internal"/>
        <Using Include="Rxmxnx.PInvoke.Internal.FrameworkCompat"/>
        <Using Include="Rxmxnx.PInvoke.Internal.Localization"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\Intermediate\Rxmxnx.PInvoke.Common.Intermediate\Rxmxnx.PInvoke.Common.Intermediate.csproj"/>
    </ItemGroup>

</Project>
