<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <LangVersion Condition="'$(MSBuildVersion)' &lt; '16.8.0'">8.0</LangVersion>
        <LangVersion Condition="'$(LangVersion)' != '8.0'">9.0</LangVersion>
        <TargetFrameworks>netcoreapp2.1;net461;net462;net470;net472</TargetFrameworks>
        <TargetFrameworks Condition="$([MSBuild]::IsOSPlatform('WINDOWS')) And '$(Version)' != ''">$(TargetFrameworks);uap10.0.16299</TargetFrameworks>
        <Nullable>enable</Nullable>
        <ImplicitUsings>disable</ImplicitUsings>
        <CheckEolTargetFramework>false</CheckEolTargetFramework>
        <Deterministic>True</Deterministic>
        <Optimize>true</Optimize>
        <DefineConstants Condition="'$(LangVersion)' == '9.0'">$(DefineConstants);CSHARP9_0</DefineConstants>
        <AutoGenerateBindingRedirects>true</AutoGenerateBindingRedirects>
    </PropertyGroup>

    <Import Project="..\..\..\Packages.props"/>
    <Import Project="..\..\PackageReference.props"/>

    <ItemGroup>
        <Compile Include="$(MSBuildThisFileDirectory)\..\Rxmxnx.PInvoke.ApplicationTest\**\*.cs"
                 Exclude="$(MSBuildThisFileDirectory)\..\Rxmxnx.PInvoke.ApplicationTest\obj\**\*.cs"/>
    </ItemGroup>
    <ItemGroup Condition="'$(TargetFramework)' == 'netcoreapp2.0' Or '$(TargetFramework)' == 'uap10.0.16299'">
        <ProjectReference Include="$(MSBuildThisFileDirectory)\..\..\MonoFacades\Rxmxnx.PInvoke.Json\Rxmxnx.PInvoke.Json.csproj"/>
    </ItemGroup>

    <ItemGroup Condition="'$(TargetFramework)' == 'uap10.0.16299' Or '$(TargetFramework)' == 'netcoreapp2.0'">
        <PackageReference Include="System.Memory" Version="4.5.5"/>
        <PackageReference Include="System.Buffers" Version="4.5.1"/>
        <PackageReference Include="System.Threading.Tasks.Extensions" Version="4.5.4"/>
    </ItemGroup>
    <ItemGroup Condition="'$(TargetFrameworkIdentifier)' == '.NETFramework' And $([MSBuild]::VersionGreaterThanOrEquals('$(TargetFrameworkVersion)', 'v4.6.2'))">
        <PackageReference Include="System.Memory" Version="4.6.3"/>
        <PackageReference Include="System.Buffers" Version="4.6.1"/>
        <PackageReference Include="System.Threading.Tasks.Extensions" Version="4.6.3"/>
    </ItemGroup>
    <ItemGroup Condition="'$(TargetFrameworkIdentifier)' == '.NETFramework' And '$(TargetFrameworkVersion)' == 'v4.6.1'">
        <PackageReference Include="System.Buffers" Version="4.5.1"/>
        <PackageReference Include="System.Threading.Tasks.Extensions" Version="4.5.4"/>
    </ItemGroup>

</Project>
