<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003">

    <Import Project="..\Packages.props"/>

    <PropertyGroup>
        <OutputType>Library</OutputType>
        <TargetFrameworks>netstandard2.1;net8.0;net9.0;net10.0</TargetFrameworks>
        <TargetFrameworks>$(TargetFrameworks);netcoreapp3.0;netcoreapp3.1;net5.0;net6.0;net7.0</TargetFrameworks>
        <TargetFrameworks>$(TargetFrameworks);netstandard2.0;netcoreapp2.1;net461;net462;net470;net472</TargetFrameworks>
        <TargetFrameworks Condition="$([MSBuild]::IsOSPlatform('WINDOWS')) And '$(Version)' != ''">$(TargetFrameworks);uap10.0.16299</TargetFrameworks>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
        <LangVersion>latest</LangVersion>
        <TrimmerSingleWarn>false</TrimmerSingleWarn>
        <NoWarn Condition="'$(TargetFramework)' == 'netcoreapp2.1' Or '$(TargetFramework)' == 'uap10.0.16299'">$(NoWarn);NETSDK1023</NoWarn>
		<CopyLocalLockFileAssemblies Condition="'$(Version)' != ''">false</CopyLocalLockFileAssemblies>
    </PropertyGroup>

    <PropertyGroup Condition="'$(TargetFramework)' == 'uap10.0.16299'">
        <TargetFrameworkIdentifier>.NETCore</TargetFrameworkIdentifier>
        <TargetFrameworkVersion>v5.0</TargetFrameworkVersion>
        <TargetFrameworkMoniker>.NETCore,Version=v5.0</TargetFrameworkMoniker>
        <TargetPlatformIdentifier>UAP</TargetPlatformIdentifier>
        <TargetPlatformVersion>10.0.16299.0</TargetPlatformVersion>
        <TargetPlatformMinVersion>10.0.16299.0</TargetPlatformMinVersion>
        <TargetPlatformMoniker>UAP,Version=10.0.16299.0</TargetPlatformMoniker>
        <NuGetTargetMoniker>UAP,Version=v10.0.16299</NuGetTargetMoniker>
        <DefineConstants>$(DefineConstants);NETFX_CORE;WINDOWS_UWP;UAP;UAP10_0_16299</DefineConstants>
        <DisableStandardFrameworkResolution>true</DisableStandardFrameworkResolution>
    </PropertyGroup>

</Project>
